### ISSUE TITLE
Fresh Issue : EventHandler::OnEvent(char const*, char const*)

### ISSUE THREAD

**Issue by nizwar** [AgoraIO-Extensions/Agora-Flutter-SDK#749]
Happened on iPhone 13 Pro Max 15.6.1
Using your master branch with #700 fixes
```yaml
  agora_rtc_engine: 
    git:
      url: https://github.com/AgoraIO/Agora-Flutter-SDK.git
      rel: master
```

As user log said, it happend once user minimize the app
<img width="1240" alt="Screen Shot 2022-08-30 at 10 04 10" src="https://user-images.githubusercontent.com/33113137/187372031-5305d470-fa41-46b5-87ab-48761aa77b6c.png">

<img width="1241" alt="Screen Shot 2022-08-30 at 10 04 40" src="https://user-images.githubusercontent.com/33113137/187372042-f751d7fa-dd7e-40d4-b4cf-b51ca4aedba4.png">
