### ISSUE TITLE
CRASHES ON WINDOWS

### ISSUE THREAD

**Issue by Princewil** [AgoraIO-Extensions/Agora-Flutter-SDK#955]
**Describe the bug**
Trying to broadcast livestream on windows crashes in both clientRoleBroadcaster and clientRoleAudience. 
 However everything works well on mobile

1. Crash debug console as clientRoleBroadcaster.
![Screenshot (15)](https://user-images.githubusercontent.com/40724883/225602314-aa12d704-efb1-41e4-856f-92872434f071.png)

**Comment by littleGnAl** [comment]
Can you share the crash dump, thanks.

**Comment by Princewil** [comment]
Well, I doubt need for that. Using the below solved it:
  ```
agora_rtc_engine:
    git:
      url: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK.git
      ref: main
```
Hence for now, I will go with the above, till you update pub.dev.
